### ISSUE TITLE
I want to join your team

### ISSUE THREAD

**Issue by kcraftcode** [Shitzu-Apes/app#1]
Hello, my name is Ethan Tan, a seasoned web full-stack developer with over 8 years of experience specializing in blockchain technology and various programming languages and frameworks. Based in Bukit Panjang, Singapore, I hold a Bachelor's degree in Computer Science from the Singapore University of Technology and Design (SUTD) and have successfully led and contributed to numerous high-quality projects in renowned companies.

**Comment by Tarnadas** [comment]
Hey, sorry but we are not hiring
